export const HospitalData: Hospital[] = [
	{
		name: "Tech Hospital",
		location: "Kwame Nkrumah University of Science And Technology",
		image: "/tech-hospital.jpeg",
		contact: "020000001",
		working_hours: "24 hrs",
		type: "Public",
		avg_waiting_time: 4,
		services: "",
		isFavourite: true,
	},
	{
		name: "Tech Hospital",
		location: "Kwame Nkrumah University of Science And Technology",
		image: "/placeholder.png",
		contact: "020000000",
		working_hours: "24 hrs",
		type: "Public",
		avg_waiting_time: 4,
		services: "",
		isFavourite: true,
	},
	{
		name: "Tech Hospital",
		location: "Kwame Nkrumah University of Science And Technology",
		image: "/placeholder.png",
		contact: "020000000",
		working_hours: "24 hrs",
		type: "Public",
		avg_waiting_time: 4,
		services: "",
		isFavourite: true,
	},
	{
		name: "Tech Hospital",
		location: "Kwame Nkrumah University of Science And Technology",
		image: "/placeholder.png",
		contact: "020000000",
		working_hours: "24 hrs",
		type: "Public",
		avg_waiting_time: 4,
		services: "",
		isFavourite: true,
	},
	{
		name: "Tech Hospital",
		location: "Kwame Nkrumah University of Science And Technology",
		image: "/placeholder.png",
		contact: "020000000",
		working_hours: "24 hrs",
		type: "Public",
		avg_waiting_time: 4,
		services: "",
		isFavourite: false,
	},
	{
		name: "Tech Hospital",
		location: "Kwame Nkrumah University of Science And Technology",
		image: "/placeholder.png",
		contact: "020000000",
		working_hours: "24 hrs",
		type: "Public",
		avg_waiting_time: 4,
		services: "",
		isFavourite: false,
	},
	{
		name: "Tech Hospital",
		location: "Kwame Nkrumah University of Science And Technology",
		image: "/placeholder.png",
		contact: "020000000",
		working_hours: "24 hrs",
		type: "Public",
		avg_waiting_time: 4,
		services: "",
		isFavourite: false,
	},
	{
		name: "Tech Hospital",
		location: "Kwame Nkrumah University of Science And Technology",
		image: "/placeholder.png",
		contact: "020000000",
		working_hours: "24 hrs",
		type: "Public",
		avg_waiting_time: 4,
		services: "",
		isFavourite: false,
	},
	{
		name: "Tech Hospital",
		location: "Kwame Nkrumah University of Science And Technology",
		image: "/placeholder.png",
		contact: "020000000",
		working_hours: "24 hrs",
		type: "Public",
		avg_waiting_time: 4,
		services: "",
		isFavourite: false,
	},
	{
		name: "Tech Hospital",
		location: "Kwame Nkrumah University of Science And Technology",
		image: "/placeholder.png",
		contact: "020000000",
		working_hours: "24 hrs",
		type: "Public",
		avg_waiting_time: 4,
		services: "",
		isFavourite: false,
	},
	{
		name: "Tech Hospital",
		location: "Kwame Nkrumah University of Science And Technology",
		image: "/placeholder.png",
		contact: "020000000",
		working_hours: "24 hrs",
		type: "Public",
		avg_waiting_time: 4,
		services: "",
		isFavourite: false,
	},
];
